version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go - b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_NAME=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

      